
[env]
TERM = "xterm-256color"

[font]
size = 15
normal = { family = "MesloLGS NF", style = "Regular" }
bold = { family = "MesloLGS NF", style = "Bold" }
italic = { family = "MesloLGS NF", style = "Italic" }
bold_italic = { family = "MesloLGS NF", style = "Bold Italic" }

[shell]
args = ["-c", "cd ~/Downloads; tmux new-session -As $USER"]
program = "/bin/zsh"

[window]
decorations = "none"
dynamic_padding = false
dynamic_title = true
opacity = 0.94
startup_mode = "Maximized"
padding = { x = 0, y = 0 }
title = "alacritty"

[[keyboard.bindings]]
chars = "\u001f"
key = "Slash"
mods = "Control"

