
[env]
TERM = "xterm-256color"

#theme = "github_dimmed"
#import = [ "~/.config/alacritty/themes/themes/github_dimmed.toml" ]

#[[colors.indexed_colors]]
#color = "0xd18616"
#index = 16

#[[colors.indexed_colors]]
#color = "0xff938a"
#index = 17

#[colors.bright]
#black = "0x636e7b"
#blue = "0x6cb6ff"
#cyan = "0x56d4dd"
#green = "0x6bc46d"
#magenta = "0xdcbdfb"
#red = "0xff938a"
#white = "0x768390"
#yellow = "0xdaaa3f"

#[colors.normal]
#black = "0x22272e"
#blue = "0x6cb6ff"
#cyan = "0x56d4dd"
#green = "0x6bc46d"
#magenta = "0xb083f0"
#red = "0xff938a"
#white = "0x768390"
#yellow = "0xc69026"

#[colors.primary]
#background = "0x22272e"
#foreground = "0x768390"

[font]
size = 15
normal = { family = "MesloLGS NF", style = "Regular" }
bold = { family = "MesloLGS NF", style = "Bold" }
italic = { family = "MesloLGS NF", style = "Italic" }
bold_italic = { family = "MesloLGS NF", style = "Bold Italic" }

[shell]
args = ["-c", "cd ~/Downloads; tmux new-session -As $USER"]
program = "/bin/zsh"

[window]
decorations = "none"
dynamic_padding = false
dynamic_title = true
opacity = 0.94
startup_mode = "Maximized"
padding = { x = 0, y = 0 }
title = "alacritty"

