- 1.1.11+dfsg-2
- _NAME: MX Keys Mini
  _absent: [hi-res-scroll, lowres-scroll-mode, hires-smooth-invert, hires-smooth-resolution, hires-scroll-mode, scroll-ratchet, smart-shift, thumb-scroll-invert,
    thumb-scroll-mode, onboard_profiles, report_rate, report_rate_extended, pointer_speed, dpi, speed-change, backlight_level, backlight_duration_hands_out,
    backlight_duration_hands_in, backlight_duration_powered, backlight-timed, led_control, led_zone_, reprogrammable-keys, persistent-remappable-keys, crown-smooth,
    divert-crown, divert-gkeys, m-key-leds, mr-key-led, gesture2-gestures, gesture2-divert, gesture2-params, sidetone, equalizer, adc_power_management]
  _battery: 0x1004
  _modelId: B36900000000
  _sensitive: {fn-swap: false, multiplatform: false}
  _unitId: 9C5ABACC
  change-host: null
  disable-keyboard-keys: {0x1: false, 0x8: false, 0x10: false}
  divert-keys: {0xe2: 0x0, 0xe3: 0x0, 0xe5: 0x0, 0xe7: 0x0, 0xe8: 0x0, 0xe9: 0x0, 0x103: 0x0, 0x108: 0x0, 0x10a: 0x0, 0x117: 0x0, 0x11c: 0x0}
  fn-swap: false
  multiplatform: 0x0
- _NAME: MX Master 3S
  _absent: [hi-res-scroll, lowres-scroll-mode, onboard_profiles, report_rate, report_rate_extended, pointer_speed, dpi, speed-change, backlight, backlight_level,
    backlight_duration_hands_out, backlight_duration_hands_in, backlight_duration_powered, backlight-timed, led_control, led_zone_, fn-swap, persistent-remappable-keys,
    disable-keyboard-keys, crown-smooth, divert-crown, divert-gkeys, m-key-leds, mr-key-led, multiplatform, gesture2-gestures, gesture2-divert, gesture2-params,
    sidetone, equalizer, adc_power_management]
  _battery: 0x1004
  _modelId: B03400000000
  _sensitive: {change-host: false, divert-keys: false, dpi: false, hires-scroll-mode: true, hires-smooth-invert: false, hires-smooth-resolution: true, reprogrammable-keys: false,
    scroll-ratchet: false, smart-shift: false, thumb-scroll-invert: false, thumb-scroll-mode: true}
  _unitId: F2735CE5
  change-host: null
  divert-keys: {0x52: 0x0, 0x53: 0x0, 0x56: 0x0, 0xc3: 0x1, 0xc4: 0x0}
  dpi: 0x3e8
  hires-scroll-mode: false
  hires-smooth-invert: false
  hires-smooth-resolution: true
  reprogrammable-keys: {0x50: 0x50, 0x51: 0x51, 0x52: 0x52, 0x53: 0x53, 0x56: 0x56, 0xc3: 0xc3, 0xc4: 0xc4}
  scroll-ratchet: 0x2
  smart-shift: 0xa
  thumb-scroll-invert: false
  thumb-scroll-mode: false
